const mongoose = require('mongoose');

const adminPromoCodeSchema = new mongoose.Schema({
    code: { type: String, required: true, unique: true }, // Code generated by admin
    discount: { type: Number, default: 0.25, required: true }, // 25% discount, for example
}, { timestamps: true });

const AdminPromoCode = mongoose.model('AdminPromoCode', adminPromoCodeSchema);

module.exports = AdminPromoCode;